function constructFig(obj)
%% Frames
homeVBox=uiextras.VBox(...
    'Parent',           obj.ParentPanel,...
    'BackgroundColor',      'w');
functionHBox=uiextras.HBox('Parent',homeVBox);
colorHBox=uiextras.HBox('Parent',homeVBox);
colorleftVBox=uiextras.VBox('Parent',colorHBox);
colorrightVBox=uiextras.VBox('Parent',colorHBox);
colorMinHBox=uiextras.HBox('Parent',colorleftVBox);
colorMaxHBox=uiextras.HBox('Parent',colorleftVBox);
colorGammaHBox=uiextras.HBox('Parent',colorrightVBox);
colormapHBox=uiextras.HBox('Parent',colorrightVBox);
set(homeVBox,'Sizes',[30,50]);
set(colorHBox,'Sizes',[-1,-1]);
set(colorleftVBox,'Sizes',[-1,-1]);
set(colorrightVBox,'Sizes',[-1,-1]);

%% uicontrols for slice control
uicontrol(...
    'Parent',       functionHBox,...
    'Style',        'PushButton',...
    'String',       'Reset',...
    'BackgroundColor','w',...
    'Callback',     @obj.reset);
% uicontrol(...
%     'Parent',       functionHBox,...
%     'Style',        'PushButton',...
%     'String',       'Hist Equal',...
%     'BackgroundColor','g',...
%     'Callback',     @obj.histEq);

set(functionHBox,'Sizes',70);

%% uicontrols for color correction
uicontrol(...
    'Parent',       colorMinHBox,...
    'Style',        'Text',...
    'String',       'Min(%)');
obj.MinValue=uicontrol(...
    'Parent',       colorMinHBox,...
    'Style',        'Edit',...
    'String',       '0',...
    'BackgroundColor','w',...
    'Callback',     @obj.checkSliderInput);
obj.SliderMin=uicontrol(...
    'Parent',       colorMinHBox,...
    'Style',        'Slider',...
    'Min',          -1,...
    'Max',          1,...
    'Value',        -1);
addlistener(obj.SliderMin,'Value','PostSet',@obj.colormap);
set(colorMinHBox,'Sizes',[40,55,-1]);

uicontrol(...
    'Parent',       colorMaxHBox,...
    'Style',        'Text',...
    'String',       'Max(%)');
obj.MaxValue=uicontrol(...
    'Parent',       colorMaxHBox,...
    'Style',        'Edit',...
    'String',       '100',...
    'BackgroundColor','w',...
    'Callback',     @obj.checkSliderInput);
obj.SliderMax=uicontrol(...
    'Parent',       colorMaxHBox,...
    'Style',        'Slider',...
    'Min',          -1,...
    'Max',          1,...
    'Value',        0);
addlistener(obj.SliderMax,'Value','PostSet',@obj.colormap);
set(colorMaxHBox,'Sizes',[40,55,-1]);

uicontrol(...
    'Parent',       colorGammaHBox,...
    'Style',        'Text',...
    'String',       'Gamma');
obj.GammaValue=uicontrol(...
    'Parent',       colorGammaHBox,...
    'Style',        'Edit',...
    'String',       '1',...
    'BackgroundColor','w',...
    'Callback',     @obj.checkSliderInput);
obj.SliderGamma=uicontrol(...
    'Parent',       colorGammaHBox,...
    'Style',        'Slider',...
    'Min',          0.01,...
    'Max',          5,...
    'Value',        1);
addlistener(obj.SliderGamma,'Value','PostSet',@obj.colormap);
set(colorGammaHBox,'Sizes',[40,55,-1]);

obj.FlipCheckbox=uicontrol(...
    'Parent',       colormapHBox,...
    'Style',        'Checkbox',...
    'String',       'flip',...
    'Callback',     @obj.colormap);
obj.ColorMap=uicontrol(...
    'Parent',       colormapHBox,...
    'Style',        'popup',...
    'String',       {...
    'gray','jet','hsv','hot','copper','cool',...
    'spring','summer','autumn','winter','cm_blackbody',...
    'cm_blue','cm_bluehot','cm_blueredgreen','cm_copper',...
    'cm_cyan','cm_cyanmagenta','cm_geo','cm_gold','cm_green',...
    'cm_landandsea','cm_magenta','cm_pastels','cm_pastelsmap',...
    'cm_planetearth','cm_rainbow','red','cm_redwhiteblue',...
    'cm_redwhitegreen','cm_relief','cm_spectrum','cm_terrain',...
    'cm_yellow','cm_yellowhot'},...
    'Callback',     @obj.colormap);
set(colormapHBox,'Sizes',[50,-1]);
end


