function tf = loadMAESTRO_fits( varargin )

% The function loadMAESTRO(filename) is designed
% to load the scienta data file generated by ALS MAESTRO labview
% software
% Input "filename" is a string that contain the full filename
% e.g. loadMAESTRO('*****.fits');
% return true if successfully loaded, otherwise return false.
%
% % bug report to: xuxiang1002@gmail.com

[~, filename, ext] = fileparts(varargin{1});
if ~isempty(str2double( filename(1) ))
    filename=['A' filename];
end

info = fitsinfo(varargin{1});
keywords_primary = info.PrimaryData.Keywords;
keywords_binarytable = info.BinaryTable.Keywords;

travel = 'asdf'; %initial random value
tdelt = 'asdf';

for ii = 1:size(keywords_binarytable,1)
    keyword = keywords_binarytable{ii,1};
    if strncmp(keyword,'TDIM',4)
        tmp = sscanf(keywords_binarytable{ii,2},'(%d,%d)');
        nx = tmp(1);
        ny = tmp(2);
        number = keyword (5);
        travel = ['TRVAL',number];
        tdelt = ['TDELT',number];
    elseif strncmp(keyword,travel,6)
        tmp = sscanf(keywords_binarytable{ii,2},'(%f,%f)');
        x0 = tmp(1);
        y0 = tmp(2);
    elseif strncmp(keyword,tdelt,6)
        tmp = sscanf(keywords_binarytable{ii,2},'(%f,%f)');
        dx = tmp(1);
        dy = tmp(2);
    end
end

% pixel to degree
xend = x0+dx*(nx-1);
data.x = linspace(x0,xend,nx);
anglePerPixel = 0.04631; % to be determined
centerPixel = (x0+xend)/2;
data.x = (data.x - centerPixel).*anglePerPixel;
% y axis energy
yend = y0+dy*(ny-1);
data.y = linspace(y0,yend,ny);

fitsdata = fitsread(varargin{1},'binarytable','info',info);
if size(fitsdata{2},1) == 1
    % determine dimension
    dim = 2;
else
    dim = 3;
end
switch dim
    case 2
        data.value = reshape(fitsdata{end},nx,ny);
    case 3
        data.z = data.y;
        nz = ny;
        data.y = data.x;
        ny = nx;
        data.x = fitsdata{2}';
        nx = length(fitsdata{2});
        data.value = reshape(fitsdata{end},nx,ny,nz);
end

assignin('base', filename, data);

tf = true;
