function figureConstruct( obj )
%% Basic Layout
obj.Figure = figure('Position',[500 200 800 600],...
    'Name','DispersionReconstruction',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'IntegerHandle','off',...
    'HandleVisibility','off',...
    'Tag','DispersionReconstruction');
VBox=uiextras.VBox('Parent',obj.Figure,...
    'BackgroundColor','w');
HBoxControl=uiextras.HBox('Parent',VBox,...
    'BackgroundColor','w');
HBoxAxis=uiextras.HBox('Parent',VBox,...
    'BackgroundColor','w');
VBox1=uiextras.VBox('Parent',HBoxControl,...
    'BackgroundColor','w');
set(VBox,'Sizes',[160,-1]);
%% VBox1
obj.PbGetFromWorkspace = uicontrol(...
    'Parent',       VBox1,...
    'Style',        'Pushbutton',...
    'String',       '<html>Get Data From<br>Workspace',...
    'Callback',     @obj.getFromWorkspace);
obj.PbRender = uicontrol(...
    'Parent',       VBox1,...
    'Style',        'Pushbutton',...
    'String',       'Render Data',...
    'Callback',     @obj.render);
obj.PbFit = uicontrol(...
    'Parent',       VBox1,...
    'Style',        'Pushbutton',...
    'String',       'Fit Parameters',...
    'Callback',     @obj.fitPar);
rname = {'Figure Num'};
tabledata = ...
    {'100'};
cformat = {'Char'};
obj.Table = uitable(...
    'Parent',VBox1,...
    'Data',tabledata,...
    'ColumnName',rname,...
    'ColumnFormat',cformat,...
    'RowName',[],...
    'ColumnEditable',true);
%% HBoxControl, Right Side
cname = {'Value','Hold','Bound1','Bound2'};
rname = {'Ef','Temperature','Ew','dE','dK','p','m'};
cformat = {'Char','logical','Char','Char'};
tabledata = ...
    {'0' true '-inf' 'inf';...
    '10' true '2' '250';...
    '0.1' false '0.001' '0.2';...
    '0.007' false '0.001' '0.05';...
    '0.005' false '0.001' '0.05';...
    '38,0,-0.19' false '25,0,-0.25' '80,0,-0.10';...
    '0' true '0' '0';};
w=50;
tooltipstr='p: y=p(i)*x^(n-i)+...+p(n-1)*x^1+p(n)*x^0. m is mask';
obj.ParameterTable = uitable(...
    'Parent',HBoxControl,...
    'Data',tabledata,...
    'ColumnName',cname,...
    'RowName',rname,...
    'ColumnFormat',cformat,...
    'ColumnWidth',{3*w w w w},...
    'ColumnEditable',[true true true true],...
    'TooltipString',tooltipstr);
set(HBoxControl,'Sizes',[100,-1]);
%% HBoxAxis
Panel1 = uipanel(...
    'Parent',HBoxAxis,...
    'Title','Original Data');
Panel2 = uipanel(...
    'Parent',HBoxAxis,...
    'Title','Rendered Data');
obj.Axis1=axes('Parent',Panel1);
obj.Axis2=axes('Parent',Panel2);
end