function figureConstruct(obj)
obj.Figure = figure('Position',[500 100 350 600],...
    'Name','FitFermiSurface',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'IntegerHandle','off',...
    'HandleVisibility','off',...
    'Tag','FitFermiSurface');
VBox=uiextras.VBox('Parent',obj.Figure,...
    'BackgroundColor','w');
HBox1=uiextras.HBox('Parent',VBox,...
    'BackgroundColor','w');
HBox2=uiextras.HBox('Parent',VBox,...
    'BackgroundColor','w');
HBox3=uiextras.HBox('Parent',VBox,...
    'BackgroundColor','w');
HBox4=uiextras.HBox('Parent',VBox,...
    'BackgroundColor','w');
set(VBox,'Sizes',[50,60,160,-1]);
%% HBox1
obj.PbGetFromFigure = uicontrol(...
    'Parent',       HBox1,...
    'Style',        'Pushbutton',...
    'String',       '<html>Get EDC From<br> Figure',...
    'Callback',     @obj.getFromFigure);
obj.PbGetFromWorkspace = uicontrol(...
    'Parent',       HBox1,...
    'Style',        'Pushbutton',...
    'String',       '<html>Get EDC From<br>Workspace',...
    'Callback',     @obj.getFromWorkspace);
obj.PbFit = uicontrol(...
    'Parent',       HBox1,...
    'Style',        'Pushbutton',...
    'String',       'Fit FS',...
    'Callback',     @obj.fit);
obj.PbCorrect = uicontrol(...
    'Parent',       HBox1,...
    'Style',        'Pushbutton',...
    'String',       'Corr FS',...
    'Callback',     @obj.corr);
obj.PbOffset = uicontrol(...
    'Parent',       HBox1,...
    'Style',        'Pushbutton',...
    'String',       'Offset Energy Axis',...
    'Callback',     @obj.offset_Eaxis);

%% HBox2
rname = {'Figure Num','Energy Min','Energy Max'};
tabledata = ...
    {num2str(get(gcf,'Number'));'Min';'Max'};
cformat = {'Char'};
obj.Table = uitable(...
    'Parent',HBox2,...
    'Data',tabledata,...
    'ColumnName',[],...
    'ColumnFormat',cformat,...
    'RowName',rname,...
    'ColumnEditable',true);
%% HBox3
cname = {'Value','Hold','Bound1','Bound2'};
rname = {'Ef','Temperature','Energy Res','a0','E0','V0','Background'};
cformat = {'numeric','logical','numeric','numeric'};
tooltipstr='Value=bk+(a0*(y-E0)+V0)./(exp((y-Ef)/kT)+1)';
tabledata = ...
    {0 false -inf inf;...
    70 false 5 50;...
    0.005 false 0 0.1;...
    1 false -inf inf;...
    0 false '-' '-';...
    0 false '-' '-';...
    0 false '-' '-';};
w=50;
obj.ParameterTable = uitable(...
    'Parent',HBox3,...
    'Data',tabledata,...
    'ColumnName',cname,...
    'RowName',rname,...
    'ColumnFormat',cformat,...
    'ColumnWidth',{w w w w},...
    'ColumnEditable',[true true true true],...
    'TooltipString',tooltipstr);
%% HBox4
obj.Axis = axes('Parent',HBox4);
end