function figureConstruct(obj)
obj.Figure=figure('Name','Fermi Dirac Distribution Correction');
obj.Data.x=(1:1000)/1000*3-3;
obj.Data.y=(cos(obj.Data.x*2*pi/3)+1)/2;
obj.Data.y=obj.Data.y*1./(exp((obj.Data.x-(-1))/100/8.617e-5)+1);

homeHBox=uiextras.HBox(...
    'Parent',           obj.Figure);
controlPanel=uiextras.Panel(...
    'Parent',           homeHBox,...
    'Title',            'Control');
axisPanel=uiextras.Panel(...
    'Parent',           homeHBox,...
    'Title',            'EDC');
set(homeHBox,'Sizes',[100,-1]);

%% controlVBox
controlVBox=uiextras.VBox(...
    'Parent',           controlPanel);
obj.InputFigureNum=uicontrol(...
    'Parent',           controlVBox,...
    'Style',            'Edit',...
    'String',           '100');
obj.SelectFigure=uicontrol(...
    'Parent',           controlVBox,...
    'Style',            'PushButton',...
    'String',           '<html>Get EDC From<br> Figure',...
    'CallBack',         @obj.getEDCFromFigure);
obj.SelectVariable=uicontrol(...
    'Parent',           controlVBox,...
    'Style',            'PushButton',...
    'String',           '<html>Get EDC From<br> Workspace',...
    'CallBack',         @obj.getEDCFromVariable);
uicontrol(...
    'Parent',           controlVBox,...
    'Style',            'Text',...
    'String',           'Direction');
obj.SelectDirection=uicontrol(...
    'Parent',           controlVBox,...
    'Style',            'PopupMenu',...
    'String',           {'x-y','y-x'},...
    'CallBack',         @obj.plot);
uicontrol(...
    'Parent',           controlVBox,...
    'Style',            'Text',...
    'String',           'Temperature');
obj.InputTemperature=uicontrol(...
    'Parent',           controlVBox,...
    'Style',            'edit',...
    'String',           '100.0',...
    'CallBack',         @obj.plot);
uicontrol(...
    'Parent',           controlVBox,...
    'Style',            'Text',...
    'String',           'Energy Resolution');
obj.InputEnergyResolution=uicontrol(...
    'Parent',           controlVBox,...
    'Style',            'edit',...
    'String',           '0.10',...
    'CallBack',         @obj.plot);
uicontrol(...
    'Parent',           controlVBox,...
    'Style',            'Text',...
    'String',           'Ef');
obj.InputEf=uicontrol(...
    'Parent',           controlVBox,...
    'Style',            'edit',...
    'String',           '-1',...
    'CallBack',         @obj.plot);
uicontrol(...
    'Parent',           controlVBox,...
    'Style',            'Text',...
    'String',           'Threshold');
obj.InputThreshold=uicontrol(...
    'Parent',           controlVBox,...
    'Style',            'edit',...
    'String',           '0.005',...
    'CallBack',         @obj.plot);
set(controlVBox,'Sizes',[30,60,60,20,30,20,30,20,30,20,30,20,30]);
% End of controlVBox

%% axisPanel
obj.Axis=axes(...
    'Parent',           axisPanel);

obj.plot;
end

